provider :
  region : ca-central-1
rules :

#VPC
- aws-vpc-flow-logs-are-enabled: {}
#DynamoDB
- aws-dynamodb-encryption :
    whitelist:
      - pipeline-services-dev
- aws-dynamodb-has-required-tags: 
    tags:
      - key: env
        regex: (dev|test|prod)       
- aws-dynamodb-point-in-time-recovery:
    exclude :
      - pipeline-services-dev
#S3
- aws-s3-naming-conventions:
    regex: ".+-bucket$"
- aws-s3-bucket-encryption: {}
- aws-s3-bucket-public-access-block: {}
- aws-s3-bucket-versioning: {}
- aws-s3-bucket-ensure-logging-is-enabled: {}
- aws-s3-bucket-has-required-tags: 
    tags:
      - key: env
        regex: (dev|test|prod)
