provider :
  region : ca-central-1
rules :
#DynamoDB
- aws-dynamodb-has-required-tags: 
    tags:
      - key: env
        regex: (dev|test|prod)       
#S3
- aws-s3-bucket-versioning: {}
- aws-s3-bucket-ensure-logging-is-enabled: {}
